name: Update locked envs
on:
  push:
    paths:
    - pyproject.toml
  workflow_dispatch:

jobs:
  update-uv-locked-environment:
    if: ${{ github.ref == 'refs/heads/main' }}
    name: Update pinned envs for uv
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Install uv
      uses: astral-sh/setup-uv@v6

    - name: Generate lockfile for uv
      run: |
        uv lock --upgrade

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: lockfiles-uv
        path: uv.lock

  create-pull-request:
    needs:
    - update-uv-locked-environment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Download uv artifacts
      uses: actions/download-artifact@v5
      with:
        name: lockfiles-uv

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v7
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: update-locked-environment
        title: "[github-actions.ci] Update locked envs"
        body: |
          Automatically generated PR to update locked environment files.

          **Note: Do not merge without manual test execution. Either update the branch to trigger tests, or use `workflow_dispatch` to run tests manually. Unlike standard PRs, tests will not run automatically.**
        commit-message: "update uv-lock"
